invoice/urls.py
from django.urls import path, include

from . import views

app_name = 'invoice'

urlpatterns = ([
    path('login/', views.login, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/invoices', views.invoices, name='invoices'),
    path('dashboard/productsOrServices', views.products_or_services, name='products_or_services'),
    path('dashboard/clients', views.clients, name='clients'),
])

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from invoice import views

urlpatterns = ([
    path('admin/', admin.site.urls),

    # -- INVOICE URLS --
    path('', views.index, name='index'),
    path('', include('invoice.urls')),
])

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8"/>
    <meta
            name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>

    <!--TITLE-->
    <title>{% block title %}{% endblock title %} | NFDEV Invoice</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'assets/css/dashboard.css' %}" rel="stylesheet">

    <!--CSS-->
    <link href="{% static 'assets/base.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}

    <!-- JS starts here  -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
            integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
            integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"
            defer></script>
    <script src="{% static 'assets/js/dashboard.js' %}" defer></script>

    {% block scripts %}{% endblock %}
    <!-- JS ends here  -->
</head>
<body>

    {% block navbar %} {% endblock navbar %}

    {% block header %} {% endblock header %}

    {% block main %} {% endblock main %}

    {% include "base/footer.html" %}

</body>
</html>

templates/base/footer.html
<footer>

</footer>

templates/base/navbar.html
<nav class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <p><a href="/">LOGO</a></p>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                <li><a href="#" class="nav-link px-2 text-white">About</a></li>
            </ul>

            <div class="text-end">
                <a href="{% url 'invoice:login' %}">
                    <button type="button" class="btn btn-primary">Login</button>
                </a>
            </div>
        </div>
    </div>
</nav>

templates/base/navbarUserConnected.html
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Welcome : {{ user.username }}</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="">Log Out</a>
        </div>
    </div>
</nav>

templates/base/sidebar.html
<!--Sidebar starts-->
<aside class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:dashboard' %}">
                            <span data-feather="home"></span>
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:invoices' %}">
                            <span data-feather="file"></span>
                            Invoices
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:products_or_services' %}">
                            <span data-feather="shopping-cart"></span>
                            Products / Services
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:clients' %}">
                            <span data-feather="users"></span>
                            Clients
                        </a>
                    </li>

                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Settings</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Company
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            SMTP
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span data-feather="file-text"></span>
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</aside>
<!--Sidebar ends-->